/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/xYHqD5MkVkT
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import Image from "next/image"
import logo2 from "@/public/blume-logo-4.png"
import { FaLinkedinIn } from "react-icons/fa";


export function Navbar() {
  return (
    <nav className="fixed inset-x-0 top-0 z-50 shadow-md  bg-white  dark:bg-gray-950/90">
      <div className="w-full max-w-7xl mx-auto px-4">
        <div className="flex justify-between h-14 items-center ">
          <Link className="flex items-center" href="https://blume.vc/" target="_blank">
            <Image src={logo2} alt="blume" width="100" height="80"  />
           
          </Link>
          <nav className="hidden md:flex gap-4">
            <Link className="font-medium flex items-center text-sm transition-colors hover:underline" href="https://github.com/HarshJ23/flask-app-blume/blob/main/README.md" target="_blank">
              Project details
            </Link>
            <Link className="font-medium flex items-center text-sm transition-colors hover:underline" href="https://github.com/HarshJ23/flask-app-blume" target="_blank">
              Github repo
            </Link>
            <Link className="font-medium flex items-center text-sm transition-colors hover:underline" href="https://docs.google.com/document/d/1yciGXF82lhsLxyushtW69DoDSfirXT7XRRVulz_8Xx8/edit?usp=sharing" target="_blank">
              Usecase doc
            </Link>
            <Link className="font-medium flex items-center text-sm transition-colors hover:underline" href="https://github.com/lerocha/chinook-database/tree/master?tab=readme-ov-file#data-model" target="_blank">
              Open-source sample database
            </Link>
          </nav>
          <div className="flex items-center gap-4">
            
            <Link href="https://www.linkedin.com/in/harsh-jawajiwar-086320215/" target="_blank">
            <Button ><FaLinkedinIn  className="text-xl"/></Button>
            </Link>
          </div>
        </div>
      </div>
    </nav>
  )
}